### ISSUE TITLE
Test failed:

### ISSUE THREAD

**Issue by titovanton** [google/gdata-python-client#32]
======================================================================
FAIL: testRecordResponse (atom_tests.mock_http_test.MockHttpClientUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/titovanton/gdata-python-client/tests/atom_tests/mock_http_test.py", line 49, in testRecordResponse
    self.assertEquals(live_response.status, 200)
AssertionError: 404 != 200

----------------------------------------------------------------------
Ran 3 tests in 0.879s

FAILED (failures=1)
Traceback (most recent call last):
  File "tests/run_data_tests.py", line 57, in <module>
    RunAllTests()
  File "tests/run_data_tests.py", line 54, in RunAllTests
    test_runner.RunAllTests()
  File "/home/titovanton/gdata-python-client/tests/module_test_runner.py", line 58, in RunAllTests
    raise Exception('Tests failed!')
Exception: Tests failed!

**Comment by r0nni3** [comment]
I'm having the same problem.

``` console
...
FAIL: testRecordResponse (atom_tests.mock_http_test.MockHttpClientUnitTest)
...
``` 

but in the traceback of the error, outputs:
``` console
...
Traceback (most recent call last):
    File "/Users/ronnie/Development/ContactSergeant/gdata-python-client/tests/atom_tests/mock_http_test.py", line 49, in testRecordResponse
...
```

In that file where the error occurs, two line above where de error occurs, line 47, there is a GET request to an url that apparently is not working. [Broken URL](http://www.google.com/base/feeds/snippets?max-results=1)
``` python
...
     live_response = self.client.request('GET',
         'http://www.google.com/base/feeds/snippets?max-results=1') #line 47
     live_response_body = live_response.read()
     self.assertEquals(live_response.status, 200) #line 49
...
```

Hope this helps to get the notification to the appropriate person.

**Comment by msjaiswal** [comment]
Beating the drums again. Hoping to get more priority to this one. Thanks.
