### ISSUE TITLE
ImportError: No module named tlslite.utils

### ISSUE THREAD

**Issue by harshparmar** [google/gdata-python-client#44]
import gdata.spreadsheet.service

import sys
import string
import json

with open("GoogleAppPw.json") as fh:
    config = json.load(fh)

client = gdata.spreadsheet.service.SpreadsheetsService()

client.ClientLogin(config['email'], config['password'])
###### ##############OUTPUT

Traceback (most recent call last):
  File "addcolumn.py", line 1, in <module>
    import gdata.spreadsheet.service
  File "/Library/Python/2.7/site-packages/gdata/spreadsheet/service.py", line 32, in <module>
    import gdata.service
  File "/Library/Python/2.7/site-packages/gdata/service.py", line 80, in <module>
    import gdata.auth
  File "/Library/Python/2.7/site-packages/gdata/auth.py", line 29, in <module>
    import gdata.oauth.rsa as oauth_rsa
  File "/Library/Python/2.7/site-packages/gdata/oauth/rsa.py", line 10, in <module>
    from tlslite.utils import keyfactory
ImportError: No module named tlslite.utils

**Comment by harishr1308** [comment]
http://www.digi.com/wiki/developer/index.php/Tlslite
[tlslite-0.3.8.tar.gz](https://github.com/google/gdata-python-client/files/282611/tlslite-0.3.8.tar.gz)

just download the tar file and run
python setup.py install

**Comment by danielowen11** [comment]
I got the same error, when trying to run tests using `/tests/run_data_tests.py`. Seems like `tlslite` isn't part of python 2.7, shouldn't it be listed as a dependency?

**Comment by andremmaia** [comment]
install or upgrade your tlslite using pip

if you can install use:
**pip install tlslite**

if you can update use:
**pip install --upgrade tlslite**

**Comment by hagayo** [comment]
**Adding tlslite to src/gdata directory to solve import errors**
When adding tlslite directory into /src/gdata, the factory-key is found
and import errors are solved...  ;-)
