### ISSUE TITLE
large file download fails with OverflowError

### ISSUE THREAD

**Issue by rupertlevene** [google/gdata-python-client#5]
Files in Google Drive which are more than 2GB fail to download on my 32 bit Linux machine.

$ python gdata-get.py
Traceback (most recent call last):
  File "gdata-get.py", line 129, in <module>
    g._get('bigvid.avi', '/mnt/bigstore/tmp/testbigdownload.avi') 
  File "gdata-get.py", line 79, in _get
    self.client.DownloadResource(entry, local_path) #.name)
  File "/usr/local/lib/python2.7/dist-packages/gdata/docs/client.py", line 369, in download_resource
    self._download_file(uri, file_path, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdata/docs/client.py", line 468, in _download_file
    f.write(self._get_content(uri, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/gdata/docs/client.py", line 451, in _get_content
    return server_response.read()
  File "/usr/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 624, in _read_chunked
    return ''.join(value)
OverflowError: join() result is too long for a Python string

This issue came to light when I was using duplicity; the script gdata-get.py is a simplified version of some code from duplicity. To exhibit the issue, I first uploaded a large video (2,792,304,612 bytes) to /test-gdata/bigvid.avi in Google Drive, and added the appropriate authentication strings to line 49 of gdata-get.py. The destination filename in the final line should also be edited.

I have pastebinned gdata-get.py here: http://pastebin.com/mFK8TQiG

Version info:

$ pip search gdata|grep INSTALLED
  INSTALLED: 2.0.18 (latest)
$ apt-cache policy python|grep Installed
  Installed: 2.7.3-0ubuntu2.2
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"

**Comment by aliafshar** [comment]
For drive API, please use the drive api with google-api-python-client

https://github.com/google/google-api-python-client
