### ISSUE TITLE
import gdata not work

### ISSUE THREAD

**Issue by ossarotte** [google/gdata-python-client#59]
import gdata
Traceback (most recent call last):

  File "<ipython-input-1-fc99779d388d>", line 1, in <module>
    import gdata

  File "C:\ProgramData\Anaconda2\lib\site-packages\gdata\__init__.py", line 108, in <module>
    class LinkFinder(atom.LinkFinder):

AttributeError: 'module' object has no attribute 'LinkFinder'

when i try to import gdata this is the error

**Comment by ossarotte** [comment]
i remove atom and gdata  and reinstall whit pip install gdata

**Comment by isaacrivas10** [comment]
Have the same problem over here. Any solutions?
