### ISSUE TITLE
Error message optional_warn_function.func_name = f.func_name     AttributeError: 'function' object has no attribute 'func_name'

### ISSUE THREAD

**Issue by mcdonc** [google/gdata-python-client#65]
_From @idesignedme on July 27, 2016 2:11_

I am trying to use the google client api for python 3.5 but only 3.4 is supported I keep getting the error messag

optional_warn_function.func_name = f.func_name
    AttributeError: 'function' object has no attribute 'func_name'

is there a work around or will the version compatible with 3.5 be coming out soon ?

_Copied from original issue: google/google-api-python-client#254_

**Comment by mcdonc** [comment]
_From @theacodes on July 27, 2016 16:48_

Can we get a full stacktrace here so we know where this occurred?

Additionally, I'm happy to review any PRs to fix this.

**Comment by mcdonc** [comment]
_From @idesignedme on August 5, 2016 20:54_

@jonparrott heres what I get if I use python shell and try to import it. I get this error message

Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/gdata/**init**.py", line 27, in <module>
        import atom
      File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/atom/**init**.py", line 133, in <module>
        CreateClassFromXMLString)
      File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/atom/**init**.py", line 97, in mark_deprecated
        optional_warn_function.func_name = f.func_name
    AttributeError: 'function' object has no attribute 'func_name'

EDIT I just read this on git

The client library is only designed for Python 2.4 - 2.6. See Issue 229: 
http://code.google.com/p/gdata-python-client/issues/detail?    

id=229&q=label:Type-Defect

It also support 2.6+ but not 3.\* as yet. For 3.0 support please track 
http://code.google.com/p/gdata-python-client/issues/detail?id=229

So this may be my issue. This is from may 25, 2015

The documentation says up to 3.4 I'm using 3.5 so I guess it won't work

**Comment by mcdonc** [comment]
_From @theacodes on August 8, 2016 17:59_

Gotcha. Seems like func_name is gone in 3.5. Should be an easy fix. Happy to review any PRs to fix it.

**Comment by mcdonc** [comment]
_From @idesignedme on August 12, 2016 12:17_

@jonparrott how do I go about this I'm new to programming even newer to using git hub. How do I make a pull request?

**Comment by mcdonc** [comment]
_From @theacodes on August 12, 2016 16:10_

@idesignedme welcome to open-source. I can try to point you in the right direction, but there's a lot of stuff to cover!

I'd recommend starting with [github's guide](https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/) on collaborating. :)

**Comment by mcdonc** [comment]
_From @WinterIsComming on September 12, 2016 18:19_

Hi Any solution for this error

**Comment by mcdonc** [comment]
This bug is filed against the wrong repository, I believe.  It should be in https://github.com/google/gdata-python-client .  I think there may be an official way to move it there, but it's not immediately obvious how to do that.

**Comment by mcdonc** [comment]
This issue was moved from google-api-python-client using https://github-issue-mover.appspot.com/ so its original commenter identities have been lost, converted to @ mentions

**Comment by jloehel** [comment]
It should be `<function>.__name__` not `<function>.func_name` in python3, right?

https://docs.python.org/3/whatsnew/3.0.html#miscellaneous-other-changes

**Comment by eldhoshaji** [comment]
Try installing gdata with the following command,
pip install gdata-python3
