### ISSUE TITLE
install_requires unknown distribution option.

### ISSUE THREAD

**Issue by fionaguoguolu** [google/gdata-python-client#66]
~/gdata-python-client$ sudo python setup.py install

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'

**Comment by fionaguoguolu** [comment]
$ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/gdata-2.0.18.egg-info
Writing /usr/local/lib/python2.7/dist-packages/gdata-2.0.18.egg-info
$ ./tests/run_data_tests.py 
Traceback (most recent call last):
  File "./tests/run_data_tests.py", line 19, in <module>
    import gdata_tests.auth_test
  File "/usr/local/google/home/ggl/gdata-python-client/tests/gdata_tests/auth_test.py", line 24, in <module>
    import gdata.auth
  File "/usr/local/lib/python2.7/dist-packages/gdata/auth.py", line 29, in <module>
    import gdata.oauth.rsa as oauth_rsa
  File "/usr/local/lib/python2.7/dist-packages/gdata/oauth/rsa.py", line 10, in <module>
    from tlslite.utils import keyfactory
ImportError: No module named tlslite.utils

**Comment by fionaguoguolu** [comment]
in setup.py, replacing
`
from distutils.core import setup
`
with
`
from setuptools import setup
`
solved the problem.
